name: Build and test
on:
  workflow_call:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - bugfix/*
      - feature/*
      - release/*
      - chore/*
      - security/*

permissions:
  contents: read

jobs:
  sdist:
    name: Build sdist wheel
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: build sdist
      run: |
        make preprocess
        pip install build
        python -m build --sdist
        pip install ./dist/*.tar.gz

    - name: upload artifacts
      uses: actions/upload-artifact@v4  # https://github.com/actions/upload-artifact/issues/478
      with:
        name: curl_cffi-${{ github.sha }}-sdist.zip
        path: ./dist/*.tar.gz

  bdist:
    name: Build bdist wheels and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-14]
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # macOS make is too old
    - if: runner.os == 'macOS'
      run: |
        brew install make automake libtool

    - name: Build and test wheels
      uses: pypa/cibuildwheel@v3.3.1

    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3

    - uses: actions/upload-artifact@v4  # https://github.com/actions/upload-artifact/issues/478
      with:
        name: curl_cffi-${{ github.sha }}-${{ matrix.os }}.zip
        path: ./wheelhouse/*.whl

  # Make our build process future-proof
  build_latest:
    name: Build bdist on latest OSes
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # For linux, it's built inside a container, no need to test for latest versions.
        os: [macos-latest]
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # macOS make is too old
    - if: runner.os == 'macOS'
      run: |
        brew install make automake libtool

    - name: Build and test wheels
      uses: pypa/cibuildwheel@v3.3.1
